#1023
NethermindEth/warp pull request #1024
Opened 2023-04-07 14:28 UTC by jeetabhi01

Moved abibuiltins to builtinHandler directory.
resolves #1023

2023-04-07 20:36 UTC, piwonskp commented
Tests are not passing

2023-04-07 20:36 UTC, piwonskp requested changes
Tests are not passing

2023-04-10 09:54 UTC, piwonskp commented on .github/workflows/test-behaviour.yml
> +  workflow_dispatch:
Remove changes to yaml files please

2023-04-10 12:21 UTC, rodrigo-pino reviewed
You need to change as well the location where abiBuiltin is call. From `src/transpiler.ts` to `src/passes/builtinHandler/index.ts`

2023-04-11 06:34 UTC, jeetabhi01 commented
> You need to change as well the location where abiBuiltin is call. From `src/transpiler.ts` to `src/passes/builtinHandler/index.ts`

Could you please provide some more information on this one?

2023-04-11 20:09 UTC, rodrigo-pino commented
Hi @jeetabhi01 , sorry for not being clear. The way Warp work is that through several passes we handle different parts of the Solidity source code. One of those passes handle all builtins. When the pass that handled the `abi` builtin was made, it was as a standalone pass in `src/passes/abiBuiltins.ts` which get then instantiated in `src/transpiler.ts` in the `applyPasses` function. It should be instead define in `src/passes/builtinHandler/` and be called instead by the code `src/apsses/builtinHandler/index.ts`

2023-04-12 11:54 UTC, rodrigo-pino reviewed
You can try to run tests locally as well, for faster debugging

2023-04-12 11:54 UTC, rodrigo-pino commented on src/passes/export.ts
> +export * from './builtinHandler/abiBuiltins';
This export should not go here

2023-04-12 11:54 UTC, rodrodros commented on src/passes/builtinHandler/index.ts
You need to execute the `ABIBuiltint` pass in the `map` function

2023-04-12 11:54 UTC, rodrodros commented on src/passes/index.ts
> +export * from './builtinHandler/abiBuiltins';
Not here as well

2023-04-12 11:54 UTC, rodrodros commented on src/transpiler.ts
> +  // ABIBuiltins,
delete

2023-04-12 11:54 UTC, rodrodros commented on src/transpiler.ts
> +    // ['Abi', ABIBuiltins],
delete

2023-04-13 14:59 UTC, jeetabhi01 commented on src/passes/builtinHandler/index.ts
I have added the pass in the map function but ```yarn test:examples``` gave an error. Please have a look in the changes.

2023-04-13 15:11 UTC, jeetabhi01 commented on src/passes/builtinHandler/index.ts
```bash
Unexpected error during transpilation
Error: Unknown pass key: Abi in pass prerequisite of Events
```

2023-04-14 11:54 UTC, rodrigo-pino commented on src/passes/builtinHandler/index.ts
Sometimes a pass requires that the AST to be already modified in certain way to guarantee it's correct execution. What's happening here is that there is a pass that required the `abi` pass, but since it is now inside the pass that handle all builtins it won't get detected.

You should find every pass that required the abi pass, change that requirement for the builtin pass instead.

2023-04-21 15:05 UTC, rodrigo-pino commented
@jeetabhi01 do you need any more help, how it is going?

2023-04-25 04:19 UTC, jeetabhi01 commented
> @jeetabhi01 do you need any more help, how it is going?

Oh  I am sorry for late reply,
Actually I am unable to find where the individual pass is implemented I tried debugging it but couldn't find it.
```
$ bin/warp transpile exampleContracts/ERC20.sol
Unexpected error during transpilation
Error: Unknown pass key: Abi in pass prerequisite of Events
    at /home/jeet_abhi01/Documents/Projects/warp/build/utils/cli.js:45:23
    at Set.forEach (<anonymous>)
    at /home/jeet_abhi01/Documents/Projects/warp/build/utils/cli.js:43:22
    at Array.forEach (<anonymous>)
    at parsePassOrder (/home/jeet_abhi01/Documents/Projects/warp/build/utils/cli.js:40:19)
    at applyPasses (/home/jeet_abhi01/Documents/Projects/warp/build/transpiler.js:86:52)
    at transpile (/home/jeet_abhi01/Documents/Projects/warp/build/transpiler.js:14:22)
    at Command.runTranspile (/home/jeet_abhi01/Documents/Projects/warp/build/cli.js:84:36)
    at Command.listener [as _actionHandler] (/home/jeet_abhi01/Documents/Projects/warp/node_modules/commander/lib/command.js:481:17)
    at /home/jeet_abhi01/Documents/Projects/warp/node_modules/commander/lib/command.js:1236:65
    at Command._chainOrCall (/home/jeet_abhi01/Documents/Projects/warp/node_modules/commander/lib/command.js:1152:12)
    at Command._parseCommand (/home/jeet_abhi01/Documents/Projects/warp/node_modules/commander/lib/command.js:1236:27)
    at Command._dispatchSubcommand (/home/jeet_abhi01/Documents/Projects/warp/node_modules/commander/lib/command.js:1058:25)
    at Command._parseCommand (/home/jeet_abhi01/Documents/Projects/warp/node_modules/commander/lib/command.js:1201:19)
    at Command.parse (/home/jeet_abhi01/Documents/Projects/warp/node_modules/commander/lib/command.js:890:10)
    at Object.<anonymous> (/home/jeet_abhi01/Documents/Projects/warp/build/index.js:4:15)
Transpilation failed
```

2023-05-31 04:35 UTC, closed without merging