implement uint256_mod, uint256_mulmod, uint256_addmod, uint256_exp
NethermindEth/warp pull request #170
Opened 2021-12-30 13:14 UTC by BitBaseBit

2021-12-30 13:20 UTC, swapnilraj commented
can you run cairo-format and add a behaviour test

2022-01-02 13:39 UTC, murcake requested changes

2022-01-02 13:39 UTC, murcake commented on warp/cairo-src/evm/uint256.cairo
> +    return (res=res)
The implementation of `addmod` and `mulmod` is not correct. Intermediate calculations, per yellow paper, should not be subject to modulo

The counterexample: `mulmod(2**128, 2**128, 3)` should be `3`, but in this implementation it is `0`, in fact, for every `m`.

2022-01-02 13:42 UTC, murcake commented
The PR description says that it implements `uint256_exp`, but it doesn't (am I missing something?)

2022-01-02 13:44 UTC, murcake commented
Yes, sorry, it does implement exponent, I overlooked it

2022-01-02 14:17 UTC, closed without merging