Delete
NethermindEth/warp pull request #354
Opened 2022-05-18 19:00 UTC by rodrigo-pino

2022-05-18 22:01 UTC, DomHenderson commented on src/passes/references/delete.ts
>  function rejectIfUnsupported(node: ASTNode, type: TypeNode, ast: AST): void {
This commented code can be deleted now

2022-05-18 23:57 UTC, rodrigo-pino commented on src/utils/cairoTypeSystem.ts
> +// There shoudl be a way of differentiating Maps from arrays
Yeah that's a remnant code from an old thought from when I was poking that part of the project

2022-05-23 10:42 UTC, DomHenderson requested changes

2022-05-23 10:42 UTC, DomHenderson commented on src/cairoUtilFuncGen/storage/storageDelete.ts
> +    const elementTWidht = CairoType.fromSol(elementT, this.ast).width;
Fairly sure this should be TypeConversionContext.StorageAllocation

2022-05-24 11:03 UTC, DomHenderson approved these changes

2022-05-24 11:15 UTC, merged