Receive complex returns
NethermindEth/warp pull request #377
Opened 2022-05-26 11:37 UTC by DomHenderson

Fixes calldata to memory, and handles passing inputs to and receiving inputs from function calls referencing external functions

2022-05-26 21:03 UTC, GuyMcComb commented
Don't forget to merge branch `calldataRefInputs` to get the updated passes

2022-05-28 12:02 UTC, GuyMcComb submitted a review, later dismissed

2022-05-28 12:06 UTC, GuyMcComb requested changes
Just the 3 comments above.

2022-05-28 23:12 UTC, DomHenderson commented on src/cairoUtilFuncGen/calldata/externalDynArray/externalDynArrayStructConstructor.ts
> +  gen(
That's just me making it explicit that the return type is tied to which type is passed in

2022-05-29 19:20 UTC, GuyMcComb approved these changes

2022-05-29 19:28 UTC, merged