Benchmark: Separate build and benchmark
NethermindEth/warp pull request #415
Opened 2022-05-31 17:50 UTC by Glitch18

Separates the `build` and `benchmark` as two jobs

2022-05-31 19:16 UTC, BitBaseBit requested changes
Benchmarks shouldn't be running here.

2022-06-02 15:24 UTC, Glitch18 commented
Ran into a bit of CI issues. Fixing them up soon to have this merged.

2022-06-02 20:46 UTC, DomHenderson requested changes

2022-06-03 05:19 UTC, Glitch18 commented on .github/workflows/build.yml
> +          pip install cairo-lang==0.8.2
So the benchmarking uses the `generateMarkdown.py` file to convert the json into a markdown file with the stats. Although this dosen't require the cairo-lang package, but the `generateMarkdown.py` file is also used by the testnet server to record data and create the json, which requires the `TransactionExecutionInfo` object from the `starkware` package.

Hence also installing the package here to resolve the starkware imports in the file.

2022-06-03 10:51 UTC, DomHenderson approved these changes

2022-06-05 14:12 UTC, BitBaseBit approved these changes

2022-06-06 04:31 UTC, merged