Adding more unsupported features to readme
NethermindEth/warp pull request #584
Opened 2022-06-21 16:28 UTC by GuyMcComb

2022-06-21 16:35 UTC, swapnilraj approved these changes

2022-06-21 22:42 UTC, DomHenderson requested changes

2022-06-21 22:42 UTC, DomHenderson commented on readme.md
> +|         named arguments in function calls          |    :question:     |
We support things like `f({a: 3, b: 5})`, or is that not what you're referring to here?

2022-06-21 22:42 UTC, DomHenderson commented on readme.md
> +|             reverts with custom errors             |    :question:     |
We support literals as error messages for reverts

2022-06-21 22:42 UTC, DomHenderson commented on readme.md
>  |                 indexed parameters                 |        :x:        |
I know you didn't change this, but this should be changed to being worked on

2022-06-21 22:42 UTC, DomHenderson commented on readme.md
> +|               function call options                |    :question:     |
Should have an example of what this is

2022-06-21 22:42 UTC, DomHenderson commented on readme.md
> +|              nested tuple expressions              |    :question:     |
to be pedantic, this should be nested tuple assignments

2022-06-21 22:42 UTC, DomHenderson commented on readme.md
> +| member access of address object (address.balance)  |    :question:     |
this should say "e.g. address.balance" to make it clear all the address members are disallowed

2022-06-22 13:53 UTC, DomHenderson approved these changes

2022-06-22 15:13 UTC, JorikSchellekens commented
No functional changes. Skipping checks

2022-06-22 15:13 UTC, merged