Support conditionals
NethermindEth/warp pull request #615
Opened 2022-07-18 16:08 UTC by cicr99

2022-07-25 08:57 UTC, DomHenderson requested changes

2022-07-25 08:57 UTC, DomHenderson commented on src/passes/expressionSplitter/conditionalFunctionaliser.ts
> +// TODO - Check if there are any other cases where the conditional might be void
They can also be nested in other void conditionals

2022-07-25 08:57 UTC, DomHenderson commented on src/passes/rejectUnsupportedFeatures.ts
> -  visitConditional(node: Conditional, _ast: AST): void {
This should still reject non-void tuple conditionals as they aren't supported (right?). It should also reject tuple assignments that are children of anything other than an expression statement

2022-07-25 08:57 UTC, DomHenderson commented on tests/behaviour/contracts/conditionals/conditional.sol
> +  function simpleScalar(
I'd appreciate a test case that includes conditionals where both branches are literals. Ideally one for number literals as well as some for the various kinds of string literals.

2022-08-03 13:41 UTC, cicr99 commented
It was decided not to support conditionals yet due to many edge cases that can not be handled at the moment

2022-08-03 13:41 UTC, closed without merging