Unloading assignment bug
NethermindEth/warp pull request #617
Opened 2022-07-20 08:49 UTC by DomHenderson

Previously, we handled compound assignments by converting x += 1 into x = x + 1 and leaving it at that. However this meant that we converted a[i++] += 1 into a[i++] = a[i++] + 1, which is not equivalent. This fixes this by extracting volatile subexpressions like i++, but still cloning things like index accesses. This is necessary because just extracting the lhs to a constant and cloning that would assign to the 'constant', not to the element in the array

2022-07-20 17:06 UTC, GuyMcComb requested changes

2022-07-20 17:06 UTC, GuyMcComb commented on src/passes/unloadingAssignment.ts
> +      return [this.extractIndividualSubExpression(node, ast)];
Would be interested to see an example of Function(i++) being used as an lvalue or am I missing what is going on here?

2022-07-21 13:23 UTC, DomHenderson commented on src/passes/unloadingAssignment.ts
> +  ): VariableDeclarationStatement[] {
The return value is used on line 29 when we iterate through the returned array and dispatchVisit each one. Without this you can extract increment operators from inside compound assignments and then not process them

2022-07-21 13:24 UTC, GuyMcComb commented on src/passes/unloadingAssignment.ts
> +      return [this.extractIndividualSubExpression(node, ast)];
Oh I tough you were saying `getArray(i++)`

2022-07-21 13:25 UTC, GuyMcComb approved these changes

2022-07-21 13:30 UTC, DomHenderson commented
Converted to draft whilst I check one final case

2022-07-25 08:30 UTC, DomHenderson commented
Case I was concerned about is not actually valid (assignments are not lvalues), so nothing more to be added since the review

2022-07-25 08:30 UTC, merged