Interface call forwarder
NethermindEth/warp pull request #655
Opened 2022-08-17 10:53 UTC by RohitRanjangit

https://www.notion.so/nethermind/Interface-Call-forwarder-3e2c2737847f4de997a491cd964a3b30

2022-10-03 10:11 UTC, JorikSchellekens requested changes
This still needs a lot of work. The user shouldn't have to do any changes to the generated files to use them in their solidity.

2022-10-03 10:11 UTC, JorikSchellekens commented on src/interfaceCallForwarder.ts
> +class CairoContractSolWriter extends ASTNodeWriter {
Contract should include function definitions

2022-10-03 10:11 UTC, JorikSchellekens commented on src/interfaceCallForwarder.ts
> +    return createUintNTypeName(248, ast);
Type is too small, instead we should use Uint256 and do runtime bounds checking.

2022-10-03 10:11 UTC, JorikSchellekens commented on src/interfaceCallForwarder.ts
> +    return new CornerStructTypeName(ast.reserveId(), '', `<STRUCT:${cairoTypeString}>`);
`getSolTypeName` should be called recursively on the structs and create their replacement type representation in Solidity along with their bounds checking functions.

2022-10-03 10:11 UTC, JorikSchellekens commented on src/interfaceCallForwarder.ts
> +  return new CornerTypeName(ast.reserveId(), '', `<TYPE:${cairoTypeString}>`);
We should never hit this case and if we do we should throw an error

2022-10-03 10:14 UTC, JorikSchellekens commented
The output should be a Solidity contract with all the functions calls (without the address parameter) with the wrapping types and their runtime bounds checks along with all of the required struct definitions (linearised).

2022-10-17 01:33 UTC, JorikSchellekens commented
ping @RohitRanjangit

2022-10-31 12:55 UTC, RohitRanjangit commented
closed , alt to #756

2022-10-31 12:55 UTC, closed without merging