Add Abi Encode support
NethermindEth/warp pull request #657
Opened 2022-08-17 21:34 UTC by rodrigo-pino

Can now transpile:
- abi.encode
- abi.encodePacked
- abi.encodeWithSelector
- abi.encodeWithSignature

2022-08-23 10:23 UTC, GuyMcComb reviewed
Could I be a pain and ask for a test that combines dynamic types and inline types?
Such as abi.encode(uint[], unit8, uint8[]), does this increase the complexity a lot?

2022-08-24 13:12 UTC, RohitRanjangit requested changes
PR with thunders ⚡️ !!

can we have one more case in behaviour tests which involves Enums ? 

PS: Will  provide more reviews , some time later

2022-08-24 13:19 UTC, rodrigo-pino commented on src/utils/nodeTypeProcessing.ts
> +    (type instanceof UserDefinedType && type.definition instanceof EnumDefinition)
Enums cannot have more than 256 elements, so they are similar to a uint8 and that's why it's byte size is 1. Doc for reference:
https://docs.soliditylang.org/en/v0.8.16/types.html?highlight=enums#enums

2022-08-25 11:44 UTC, RohitRanjangit approved these changes

2022-08-31 15:59 UTC, GuyMcComb commented
Sem Tests Passed.

2022-09-01 12:37 UTC, cicr99 commented on src/cairoUtilFuncGen/abi/base.ts
> +      (expr) => generalizeType(getNodeType(expr, this.ast.compilerVersion))[0],
Maybe `safeGetNodeType` should be used here instead of `getNodeType`

2022-09-05 18:38 UTC, cicr99 approved these changes

2022-09-05 18:39 UTC, merged