Optimize referenced libraries pass
NethermindEth/warp pull request #688
Opened 2022-09-07 04:20 UTC by cicr99

The `ReferencedLibraries` pass adds all libraries referenced by a contract. To do so, when it encountered a function call, it would check to see if it was calling a declaration in a library, and then recursively check all function calls within that library, adding more libraries to the list. As a consequence, the resulting list might contain extra libraries, which were not actually being referenced.

The modification in the code of this pass corrects this situation. Instead of going through all the function calls inside the library, it goes through the function calls inside the referenced declaration only.

2022-09-07 12:33 UTC, RohitRanjangit requested changes
lgtm, just few suggestions

2022-09-07 12:33 UTC, RohitRanjangit commented on src/passes/referencedLibraries.ts
> +): [ASTNode, ContractDefinition] | undefined {
Just one small suggestion,   declaration should be of type  CallableDefinition instead of generalised ASTNode

2022-09-07 12:33 UTC, RohitRanjangit commented on src/passes/referencedLibraries.ts
> +  declaration: ASTNode,
ASTNode -> CallableDefinition

2022-09-07 13:48 UTC, RohitRanjangit approved these changes

2022-09-07 14:05 UTC, rodrigo-pino approved these changes
Looks good to me as well!

2022-09-07 17:46 UTC, GuyMcComb requested changes
Fails: Transpile solidity
       tests/behaviour/solidity/test/libsolidity/semanticTests/libraries/internal_library_function_bound_to_enum:

2022-09-08 16:32 UTC, closed without merging

2022-09-08 17:13 UTC, cicr99 commented
The PR was closed since it is not convenient to carry out such optimization.
When adding the library to the list of base contracts of a contract, all functions of that library are added to the contract in the `InheritanceInliner` pass, which means that all libraries that are referenced must be added, not just the ones that were found while reviewing the referenced declarations. In addition, any function that is not used or is not reachable from an externally visible function in the code will be removed in the `FunctionPruner` pass.