Adding ABI decoding for value types
NethermindEth/warp pull request #722
Opened 2022-10-04 18:43 UTC by rodrigo-pino

- [x] Sem Tests Running
- [x] Sem Tests Pass

2022-10-04 20:37 UTC, swapnilraj requested changes
Overall looks; some minor comments

2022-10-04 20:37 UTC, swapnilraj commented on src/cairoUtilFuncGen/abi/abiDecode.ts
> +        returnParams.push({ name: `result${index}`, type: cairoType.toString() });
instead of mutating the accumulator, we should use the immutable equivalent
so instead of push we should use concat or spread the original array

2022-10-04 20:37 UTC, swapnilraj commented on src/cairoUtilFuncGen/abi/abiDecode.ts
> +          `let in_range${index} =  is_le(mem_index, mem_length);`,
we should use is_le_felt here

2022-10-04 20:37 UTC, swapnilraj commented on tests/behaviour/expectations/behaviour.ts
> +              [`${BigInt(2) ** BigInt(128) - BigInt(1)}`, '0'],
tip you can write a BigInt literal by putting a `n` suffix on a number
example: BigInt(2) -> 2n

2022-10-04 20:37 UTC, swapnilraj commented on warplib/dynamic_arrays_util.cairo
> +    let (byte_power) = pow(256, power);
we can use pow2 from our warplib which is more efficient than pow

2022-10-04 20:37 UTC, swapnilraj commented on warplib/dynamic_arrays_util.cairo
> +    let firts_bytes = is_le(16, power);
is_le_felt since these are unsigned values

2022-10-04 20:37 UTC, swapnilraj commented on warplib/dynamic_arrays_util.cairo
> +    let firts_bytes = is_le(16, power);
small typo: firsts

2022-10-04 20:40 UTC, swapnilraj commented on src/passes/abiEncode.ts
> +    console.log('visiting', node.vFunctionName);
debug print

2022-10-05 17:17 UTC, GuyMcComb approved these changes

2022-10-06 14:50 UTC, swapnilraj approved these changes

2022-10-06 14:52 UTC, merged