Add test cases for safe signed addition
NethermindEth/warp pull request #728
Opened 2022-10-06 12:51 UTC by rodrigo-pino

2022-10-17 01:39 UTC, JorikSchellekens requested changes

2022-10-17 01:39 UTC, JorikSchellekens commented on tests/behaviour/expectations/utils.ts
> +export function getUint256(val: number | bigint): [string, string] {
Nitpick:
```suggestion
export function toCairoUint256(val: number | bigint): [string, string] {
```

2022-10-19 17:19 UTC, swapnilraj commented on tests/behaviour/expectations/utils.ts
> +  console.log(x);
debug log

2022-10-21 11:47 UTC, swapnilraj approved these changes

2022-10-24 13:11 UTC, merged